# -*- coding: utf-8 -*-
"""DataCleaningOpenPowerlifting2023

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hFONZrjJ_9KAJhJOVXq7dhuIurFOo49_

**August 2023 Open Powerlifting Data Analysis - DATA CLEANING**

**Data cleaning step #1: Filtering out data for a specific Event, Equipment, and Federation**
"""

import pandas as pd

path_to_csv_file = 'OpenPowerliftingRawDataAugust2023.csv'

df = pd.read_csv(path_to_csv_file)

# Filter rows based on conditions for each column
df = df[df['Event'] == 'SBD']
df = df[df['Equipment'] == 'Raw']
df = df[df['Federation'] == 'USAPL']


# Save the cleaned dataset to a new CSV file
cleaned_file_path = 'CleanedOpenPowerliftingAugust2023.csv'
df.to_csv(cleaned_file_path, index=False)

"""**Data Cleaning Step #2 -- Dropping unnecessary columns and filtering out all data before the year 2015**"""

import pandas as pd

# Replace 'path_to_cleaned_csv_file' with the actual path to your cleaned CSV file
path_to_cleaned_csv_file = 'CleanedOpenPowerliftingAugust2023.csv'

df_cleaned = pd.read_csv(path_to_cleaned_csv_file)

# List of columns to drop
columns_to_drop = ['AgeClass', 'BirthYearClass', 'Glossbrenner', 'Goodlift', 'MeetTown', 'Squat4Kg', 'Bench4Kg', 'Deadlift4Kg']


df_cleaned.drop(columns=columns_to_drop, inplace=True)

# Convert 'Date' column to datetime format
df_cleaned['Date'] = pd.to_datetime(df_cleaned['Date'], errors='coerce')


df_cleaned = df_cleaned[df_cleaned['Date'].dt.year >= 2015]

cleaned_file_path_1 = 'CleanedOpenPowerliftingAugust2023_1.csv'
df_cleaned.to_csv(cleaned_file_path_1, index=False)

"""**Data Cleaning step #3: Ordering the columns by both Name & Date**"""

import pandas as pd


path_to_cleaned_csv_file = 'CleanedOpenPowerliftingAugust2023_1.csv'


df_cleaned = pd.read_csv(path_to_cleaned_csv_file)

# Convert 'Date' column to datetime format
df_cleaned['Date'] = pd.to_datetime(df_cleaned['Date'], errors='coerce')

# Sort the DataFrame by 'Name' in alphabetical order and 'Date' from most recent to oldest
df_sorted = df_cleaned.sort_values(by=['Name', 'Date'], ascending=[True, False])


#Final Cleaned Dataset
sorted_file_path = 'FinalOpenPowerliftingAugust2023.csv'
df_sorted.to_csv(sorted_file_path, index=False)