# -*- coding: utf-8 -*-
"""Strength&Age_Breakdowns

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sbPRcuWb0yU4wst5NB4w-IvOiRcduqO3

# **Male Median Total by Age Group**
"""

import pandas as pd
import matplotlib.pyplot as plt

csv_file = 'FinalOpenPowerliftingAugust2023.csv'
df = pd.read_csv(csv_file)

df_male = df[df['Sex'] == 'M']

# Define age bins and labels
age_bins = [0, 19, 24, 29, 35, 40, 45, 50, 150]
age_labels = ['<19', '19-24', '25-29', '30-35', '36-40', '41-45', '46-50', '>50']

# Create a new column 'AgeGroup' based on age bins and labels
df_male['AgeGroup'] = pd.cut(df_male['Age'], bins=age_bins, labels=age_labels)

# Group the DataFrame by 'AgeGroup' and calculate the median 'TotalKg' for each group
median_total_kg_by_age = df_male.groupby('AgeGroup')['TotalKg'].median()


plt.figure(figsize=(10, 6))
plt.bar(age_labels, median_total_kg_by_age, color=['blue', 'green', 'orange', 'red', 'purple', 'brown', 'pink', 'gray'])
plt.xlabel('Age Group', fontsize = 16)
plt.ylabel('Median TotalKg', fontsize = 16)
plt.title('Median TotalKg by Age Group (Males)', fontsize = 20)
plt.grid(axis='y')

plt.tight_layout()
plt.show()

"""# **Female Median Total by Age Group**"""

csv_file = 'FinalOpenPowerliftingAugust2023.csv'
df = pd.read_csv(csv_file)

df_female = df[df['Sex'] == 'F']

# Define age bins and labels
age_bins = [0, 19, 24, 29, 35, 40, 45, 50, 150]
age_labels = ['<19', '19-24', '25-29', '30-35', '36-40', '41-45', '46-50', '>50']

# Create a new column 'AgeGroup' based on age bins and labels
df_female['AgeGroup'] = pd.cut(df_female['Age'], bins=age_bins, labels=age_labels)

# Group the DataFrame by 'AgeGroup' and calculate the median 'TotalKg' for each group
median_total_kg_by_age = df_female.groupby('AgeGroup')['TotalKg'].median()


plt.figure(figsize=(10, 6))
plt.bar(age_labels, median_total_kg_by_age, color=['blue', 'magenta', 'purple', 'red', 'pink', 'indigo', 'orange', 'gray'])
plt.xlabel('Age Group', fontsize = 16)
plt.ylabel('Median TotalKg', fontsize = 16)
plt.title('Median TotalKg by Age Group (Females)', fontsize = 20)
plt.grid(axis='y')

plt.tight_layout()
plt.show()

"""# **Median DOTS by Age (Males)**"""

csv_file = 'FinalOpenPowerliftingAugust2023.csv'
df = pd.read_csv(csv_file)

df_male = df[df['Sex'] == 'M']

# Define age bins and labels
age_bins = [0, 19, 24, 29, 35, 40, 45, 50, 150]
age_labels = ['<19', '19-24', '25-29', '30-35', '36-40', '41-45', '46-50', '>50']

# Create a new column 'AgeGroup' based on age bins and labels
df_male['AgeGroup'] = pd.cut(df_male['Age'], bins=age_bins, labels=age_labels)

# Group the DataFrame by 'AgeGroup' and calculate the median 'DOTS' for each group
median_dots_by_age = df_male.groupby('AgeGroup')['Dots'].median()


plt.figure(figsize=(10, 6))
plt.bar(age_labels, median_dots_by_age, color=['blue'])
plt.xlabel('Age Group', fontsize = 16)
plt.ylabel('Median DOTS', fontsize = 16)
plt.title('Median DOTS by Age Group (Males)', fontsize = 20)
plt.grid(axis='y')

plt.tight_layout()
plt.show()

"""# **Median DOTS by Age (Females)**"""

csv_file = 'FinalOpenPowerliftingAugust2023.csv'
df = pd.read_csv(csv_file)

df_female = df[df['Sex'] == 'M']

# Define age bins and labels
age_bins = [0, 19, 24, 29, 35, 40, 45, 50, 150]
age_labels = ['<19', '19-24', '25-29', '30-35', '36-40', '41-45', '46-50', '>50']

# Create a new column 'AgeGroup' based on age bins and labels
df_female['AgeGroup'] = pd.cut(df_female['Age'], bins=age_bins, labels=age_labels)

# Group the DataFrame by 'AgeGroup' and calculate the median 'DOTS' for each group
median_dots_by_age = df_female.groupby('AgeGroup')['Dots'].median()


plt.figure(figsize=(10, 6))
plt.bar(age_labels, median_dots_by_age, color=['magenta'])
plt.xlabel('Age Group', fontsize = 16)
plt.ylabel('Median DOTS', fontsize = 16)
plt.title('Median DOTS by Age Group (Females)', fontsize = 20)
plt.grid(axis='y')

plt.tight_layout()
plt.show()

"""# **Median DOTS Males 19 through 37**"""

csv_file = 'FinalOpenPowerliftingAugust2023.csv'
df = pd.read_csv(csv_file)

df_male = df[df['Sex'] == 'M']

# Define age bins and labels
age_bins = [0, 19, 22, 25, 28, 31, 34, 37, 150]
age_labels = ['<19', '19-22', '22-25', '25-28', '28-31', '31-34', '34-37', '>37']

# Create a new column 'AgeGroup' based on age bins and labels
df_male['AgeGroup'] = pd.cut(df_male['Age'], bins=age_bins, labels=age_labels)

# Group the DataFrame by 'AgeGroup' and calculate the median 'DOTS' for each group
median_dots_by_age = df_male.groupby('AgeGroup')['Dots'].median()


plt.figure(figsize=(10, 6))
plt.bar(age_labels, median_dots_by_age, color=['blue'])
plt.xlabel('Age Group', fontsize = 16)
plt.ylabel('Median DOTS', fontsize = 16)
plt.title('Median DOTS by Age Group (Males)', fontsize = 20)
plt.grid(axis='y')

plt.tight_layout()
plt.show()

"""# **Median DOTS Females age 19-37**"""

csv_file = 'FinalOpenPowerliftingAugust2023.csv'
df = pd.read_csv(csv_file)

df_female = df[df['Sex'] == 'M']

# Define age bins and labels
age_bins = [0, 19, 22, 25, 28, 31, 34, 37, 150]
age_labels = ['<19', '19-22', '22-25', '25-28', '28-31', '31-34', '34-37', '>37']

# Create a new column 'AgeGroup' based on age bins and labels
df_female['AgeGroup'] = pd.cut(df_female['Age'], bins=age_bins, labels=age_labels)

# Group the DataFrame by 'AgeGroup' and calculate the median 'DOTS' for each group
median_dots_by_age = df_female.groupby('AgeGroup')['Dots'].median()


plt.figure(figsize=(10, 6))
plt.bar(age_labels, median_dots_by_age, color=['magenta'])
plt.xlabel('Age Group', fontsize = 16)
plt.ylabel('Median DOTS', fontsize = 16)
plt.title('Median DOTS by Age Group (Females)', fontsize = 20)
plt.grid(axis='y')

plt.tight_layout()
plt.show()