# -*- coding: utf-8 -*-
"""Top&Bottom10_StateLifterCounts_Visualizations

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VDAngEu8kb9P6x3jVHzTrt9JF4Mdn9ZP

**Bar Graphs -- States with the most unique lifters since 2015**

**Horizontal Bar Graph - Top 10 States with the most Unique Lifters Since 2015**
"""

import pandas as pd
import matplotlib.pyplot as plt


path_to_csv_file = 'FinalOpenPowerliftingAugust2023.csv'

df = pd.read_csv(path_to_csv_file)

#Drop Duplicate names
df_unique_names = df.drop_duplicates(subset='Name', keep='first')

# Get the counts of unique values in the 'State' column after removing duplicates
state_counts = df_unique_names['State'].value_counts()

# Sort the state_counts Series in ascending order
state_counts_sorted = state_counts.sort_values(ascending=True)


top_25_states = state_counts_sorted.tail(10)


plt.figure(figsize=(10, 8))
top_25_states.plot(kind='barh', color=plt.cm.Paired.colors)


plt.title('Top 10 States w/the Most Lifters', fontsize=20)
plt.xlabel('Count of Lifters', fontsize=16)
plt.ylabel('State', fontsize=16)

plt.tight_layout()
plt.show()

"""# **10 States with the Least Lifters**"""

path_to_csv_file = 'FinalOpenPowerliftingAugust2023.csv'

df = pd.read_csv(path_to_csv_file)

# Drop duplicate rows based on the 'Name' column, keeping the first occurrence
df_unique_names = df.drop_duplicates(subset='Name', keep='first')


# Get the counts of unique values in the 'State' column after removing duplicates
state_counts = df_unique_names['State'].value_counts()


# Sort the state_counts Series in ascending order
state_counts_sorted = state_counts.sort_values(ascending=True)



bottom_25_states = state_counts_sorted.head(10)



plt.figure(figsize=(10, 10))
bottom_25_states.plot(kind='barh', color=plt.cm.Paired.colors)


plt.title('10 States with the Least Lifters', fontsize=20)
plt.xlabel('Count of Lifters', fontsize=16)
plt.ylabel('State', fontsize=16)


plt.tight_layout()
plt.show()

"""# **Lifter Counts Query**"""

path_to_csv_file = 'FinalOpenPowerliftingAugust2023.csv'

df = pd.read_csv(path_to_csv_file)
df_unique_names = df.drop_duplicates(subset='Name', keep='first')
state_counts = df_unique_names['State'].value_counts()


print(state_counts)